$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/v9.3.2/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: dictionary
    path: "./dictionary.txt"
    addWords: true
dictionaries:
  - dictionary
enableGlobDot: true
ignorePaths:
  - "cspell.config.yaml"
  - "dictionary.txt"
  - "**/go.mod"
  - "**/go.sum"
  - "**/.git"
  - "**/.golangci.yaml"
